/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mkk_app.JUKIR.ui;

import com.mkk_app.JUKIR.models.DateRange;
import com.mkk_app.JUKIR.models.ParkingTicket;
import com.mkk_app.JUKIR.models.Report;
import com.mkk_app.JUKIR.models.RevenueReport;
import com.mkk_app.JUKIR.models.StafKeuangan;
import com.mkk_app.JUKIR.models.Transaction;
import java.awt.Color;
import java.awt.Font;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rhaihan aditya
 */
public class FinancePanel extends javax.swing.JFrame {
    
    private StafKeuangan staf;
    private RevenueReport revenueReport;
    private DefaultTableModel tableModel;

    /**
     * Creates new form FinancePanel
     */
    public FinancePanel(StafKeuangan staf) {
        this.staf = staf;
        DateRange range = new DateRange(LocalDateTime.now().minusDays(30), LocalDateTime.now());
        this.revenueReport = new RevenueReport(range);
        initSampleData();
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Panel Keuangan - " + staf.getUsername());
        loadTableData();
        applyStyle();
    }

    private void applyStyle() {
        setSize(620, 420);
        setLocationRelativeTo(null);

        lblTotal.setFont(new Font("Dialog", Font.BOLD, 14));
        lblTotal.setForeground(new Color(0, 100, 0));

        btnGenerate.setFont(new Font("Dialog", Font.BOLD, 12));
        btnExportPDF.setFont(new Font("Dialog", Font.BOLD, 12));
        btnExportExcel.setFont(new Font("Dialog", Font.BOLD, 12));

        jTable1.setRowHeight(26);
        jTable1.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));
        jTable1.setFont(new Font("Dialog", Font.PLAIN, 12));
        jTable1.setGridColor(new Color(210, 210, 210));

        tblTransaksi.setPreferredSize(new java.awt.Dimension(500, 260));
    }
    
    private void initSampleData() {
        if (com.mkk_app.JUKIR.services.LocalStorage.getInstance().getTransactions().isEmpty()) {
            ParkingTicket t1 = new ParkingTicket("TKT-001");
            ParkingTicket t2 = new ParkingTicket("TKT-002");
            revenueReport.addTransaction(new Transaction("TX-001", 5000, t1));
            revenueReport.addTransaction(new Transaction("TX-002", 8000, t2));
            revenueReport.addTransaction(new Transaction("TX-003", 3000, t1));
        }
    }
    private void loadTableData() {
        tableModel = new DefaultTableModel(new Object[]{"ID Transaksi","Tiket","Jumlah (Rp)"}, 0);
        double total = 0;
        for (Transaction tx : revenueReport.getTxList()) {
            tableModel.addRow(new Object[]{tx.getTxId(), tx.getTicket().getTicketId(), tx.getAmount()});
            total += tx.getAmount();
        }
        jTable1.setModel(tableModel);
        lblTotal.setText("Total Pendapatan: Rp " + (long) total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        tblTransaksi = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlBtn = new javax.swing.JPanel();
        btnGenerate = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotal.setText("Total Pendapatan: Rp 0");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.setViewportView(jTable1);

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnGenerate.setText("Generate Laporan");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnExportPDF.setText("Export PDF");
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });

        btnExportExcel.setText("Export Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(tblTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerate)
                .addGap(8, 8, 8)
                .addComponent(btnExportPDF)
                .addGap(8, 8, 8)
                .addComponent(btnExportExcel)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTotal)
                .addGap(10, 10, 10)
                .addComponent(tblTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerate)
                    .addComponent(btnExportPDF)
                    .addComponent(btnExportExcel))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        Report r = staf.generateReport();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Laporan dibuat!\nID: " + r.getReportId() + "\nJudul: " + r.getTitle(),
            "Generate Laporan", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        staf.exportTo("PDF");
        revenueReport.exportTo("PDF");
        javax.swing.JOptionPane.showMessageDialog(this,
            "Laporan berhasil diekspor ke PDF.", "Export",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        staf.exportTo("Excel");
        revenueReport.exportTo("Excel");
        javax.swing.JOptionPane.showMessageDialog(this,
            "Laporan berhasil diekspor ke Excel.", "Export",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinancePanel(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JScrollPane tblTransaksi;
    // End of variables declaration//GEN-END:variables
}
